In [102]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances as ps

In [103]:
df_h = pd.read_excel(r"C:\Users\momoj\Desktop\Data sinence\AmesHousing.xlsx")
df_housing_quant = df_h[["Bedroom AbvGr", "Gr Liv Area"]].copy()
df_housing_quant["Bathrooms"] = (
    df_h["Full Bath"] +
    0.5 * df_h["Half Bath"]
)
df_housing_quant

      Bedroom AbvGr  Gr Liv Area  Bathrooms
0                 3         1656        1.0
1                 2          896        1.0
2                 3         1329        1.5
3                 3         2110        2.5
4                 3         1629        2.5
...             ...          ...        ...
2925              3         1003        1.0
2926              2          902        1.0
2927              3          970        1.0
2928              2         1389        1.0
2929              3         2000        2.5

[2930 rows x 3 columns]

In [104]:
df_h[["Gr Liv Area","Bedroom AbvGr","Full Bath","Half Bath",'TotRms AbvGrd','Garage Cars',"SalePrice"]].corr()

,Gr Liv Area,Bedroom AbvGr,Full Bath,Half Bath,TotRms AbvGrd,Garage Cars,SalePrice
Gr Liv Area,1.000000,0.516808,0.630321,0.433949,0.807772,0.488829,0.706780
Bedroom AbvGr,0.516808,1.000000,0.359489,0.247053,0.672647,0.091359,0.143913
Full Bath,0.630321,0.359489,1.000000,0.159689,0.528599,0.478182,0.545604
Half Bath,0.433949,0.247053,0.159689,1.000000,0.346493,0.233429,0.285056
TotRms AbvGrd,0.807772,0.672647,0.528599,0.346493,1.000000,0.355557,0.495474
Garage Cars,0.488829,0.091359,0.478182,0.233429,0.355557,1.000000,0.647877
SalePrice,0.706780,0.143913,0.545604,0.285056,0.495474,0.647877,1.000000

In [105]:
x = df_housing_quant.loc[2927]
x1 = df_housing_quant.loc[2928]
x -x1

Bedroom AbvGr      1.0
Gr Liv Area     -419.0
Bathrooms          0.0
dtype: float64

In [106]:
(x -x1)**2

Bedroom AbvGr         1.0
Gr Liv Area      175561.0
Bathrooms             0.0
dtype: float64

In [107]:
np.sqrt(((x - x1) ** 2).sum())

np.float64(419.0011933157231)

In [108]:
((x - x1).abs()).sum()

np.float64(420.0)

In [109]:
x = df_housing_quant.loc[2927]
x1 = df_housing_quant.loc[2928]
np.sqrt(((x - x1) ** 2).sum())

np.float64(419.0011933157231)

In [110]:
x = df_housing_quant.loc[2498]
x1 = df_housing_quant.loc[290]
np.sqrt(((x - x1) ** 2).sum())

np.float64(5.0990195135927845)

In [111]:
df_housing_st = (
(df_housing_quant - df_housing_quant.mean()) /
df_housing_quant.std()
)
df_housing_st

      Bedroom AbvGr  Gr Liv Area  Bathrooms
0          0.176064     0.309212  -1.176462
1         -1.032058    -1.194223  -1.176462
2          0.176064    -0.337661  -0.398702
3          0.176064     1.207317   1.156819
4          0.176064     0.255801   1.156819
...             ...          ...        ...
2925       0.176064    -0.982555  -1.176462
2926      -1.032058    -1.182354  -1.176462
2927       0.176064    -1.047836  -1.176462
2928      -1.032058    -0.218968  -1.176462
2929       0.176064     0.989715   1.156819

[2930 rows x 3 columns]

In [112]:
df_h_st = (df_housing_quant.
sub(df_housing_quant.mean(), axis="columns").
divide(df_housing_quant.std(), axis="columns"))
df_h_st

      Bedroom AbvGr  Gr Liv Area  Bathrooms
0          0.176064     0.309212  -1.176462
1         -1.032058    -1.194223  -1.176462
2          0.176064    -0.337661  -0.398702
3          0.176064     1.207317   1.156819
4          0.176064     0.255801   1.156819
...             ...          ...        ...
2925       0.176064    -0.982555  -1.176462
2926      -1.032058    -1.182354  -1.176462
2927       0.176064    -1.047836  -1.176462
2928      -1.032058    -0.218968  -1.176462
2929       0.176064     0.989715   1.156819

[2930 rows x 3 columns]

In [113]:
x = df_housing_st.loc[2927]
x1 = df_housing_st.loc[2928]
np.sqrt(((x - x1) ** 2).sum())

np.float64(1.465121112969562)

In [114]:
x = df_housing_st.loc[2498]
x1 = df_housing_st.loc[290]
np.sqrt(((x - x1) ** 2).sum())

np.float64(3.9440754446059385)

In [115]:

scaler = StandardScaler()
scaler.fit(df_housing_quant)
df_housing_st = scaler.transform(df_housing_quant)
df_housing_st

array([[ 0.17609421,  0.30926506, -1.17666295],
       [-1.03223376, -1.19442705, -1.17666295],
       [ 0.17609421, -0.33771825, -0.3987698 ],
       ...,
       [ 0.17609421, -1.04801492, -1.17666295],
       [-1.03223376, -0.21900572, -1.17666295],
       [ 0.17609421,  0.9898836 ,  1.1570165 ]], shape=(2930, 3))

In [116]:
x = df_housing_st[[2927, 2498], :]
x1 = df_housing_st[[2928, 290], :]
ps(x, x1)

array([[1.4653712 , 5.81988338],
       [3.17266983, 3.94474867]])